//
//  APCProperty.h
//  AutoPropertyCocoa
//
//  Created by Novo on 2019/3/14.
//  Copyright © 2019 Novo. All rights reserved.
//

#import "APCScope.h"

@class APCStringkeyString;

typedef NS_OPTIONS (NSUInteger,APCPropertyAccessOptions){
    
    APCPropertyKVCDisable          =   0,
    ///Getter from property attributes.
    APCPropertyComponentOfGetter   =   1   <<  0,
    
    APCPropertyComponentOfSetter   =   1   <<  1,
    
    APCPropertyComponentOfIVar     =   1   <<  2,
    ///Setter from property list.
    APCPropertyAssociatedSetter    =   1   <<  3,
    ///Ivar from ivar list.
    APCPropertyAssociatedIVar      =   1   <<  4,
    
    APCPropertySetValueEnable      =   APCPropertyComponentOfSetter
                                        | APCPropertyAssociatedSetter
                                        | APCPropertyComponentOfIVar
                                        | APCPropertyAssociatedIVar,
    
    APCPropertyGetValueEnable      =   APCPropertyComponentOfGetter
                                        | APCPropertyComponentOfIVar
                                        | APCPropertyAssociatedIVar,
};

typedef NS_OPTIONS(NSUInteger,APCPropertyValueKind){

    APCPropertyValueKindOfObject        =   1,
    ///C number
    APCPropertyValueKindOfNumber        =   2,
    
    APCPropertyValueKindOfStructure     =   3,
    
    APCPropertyValueKindOfSEL           =   4,
    
    APCPropertyValueKindOfPoint         =   5,
    ///char*
    APCPropertyValueKindOfCharptr       =   6,
    
    APCPropertyValueKindOfBlock         =   7,
};

typedef NS_OPTIONS(NSUInteger, APCPropertyOwnerKind){
    
    APCPropertyOwnerKindOfClass       =   0,
    
    APCPropertyOwnerKindOfInstance    =   1,
};

typedef NS_OPTIONS(NSUInteger, APCPropertyHookKind){
    
    APCPropertyHookKindOfEmpty     =   0,
    
    APCPropertyHookKindOfSelector  =   1,
    
    APCPropertyHookKindOfBlock     =   2,
    
    APCPropertyHookKindOfIMP       =   3,
};

@interface APCProperty : NSObject
{
@public
    
    NSUInteger              _hashcode;
    Class                   _des_class;
    Class                   _src_class;
    NSString*               _ori_property_name;
    NSString*               _des_getter_name;
    NSString*               _des_setter_name;
    __weak id               _instance;
@protected
    
    APCPropertyHookKind     _kindOfUserHook;
    APCPropertyOwnerKind    _kindOfOwner;
@private
    
    BOOL                    _enable;
}



@property (nonatomic,readonly)APCPropertyHookKind       kindOfUserHook;
@property (nonatomic,readonly)APCPropertyAccessOptions  accessOption;
@property (nonatomic,readonly)APCPropertyOwnerKind      kindOfOwner;
@property (nonatomic,readonly)APCPropertyValueKind      kindOfValue;
@property (nonatomic,readonly)BOOL                      isReadonly;
@property (nonatomic,readonly)objc_AssociationPolicy    policy;
@property (nonatomic,readonly)BOOL                      enable;

+ (instancetype _Nonnull)instanceWithProperty:(NSString* _Nonnull)property
                                    aInstance:(id _Nonnull)aInstance;

+ (instancetype _Nonnull)instanceWithProperty:(NSString* _Nonnull)property
                                       aClass:(Class _Nonnull __unsafe_unretained)aClass;

- (instancetype _Nonnull)initWithPropertyName:(NSString* _Nonnull)propertyName
                        aInstance:(id _Nonnull)aInstance;

- (instancetype _Nonnull)initWithPropertyName:(NSString* _Nonnull)propertyName
                                       aClass:(Class _Nonnull __unsafe_unretained)aClass;


- (id _Nullable)getIvarValueFromTarget:(_Nonnull id)target;

/**
 Return NO if the object is marked with 'id'.Return YES otherwise.
 */
@property (nullable,nonatomic,readonly)Class   propertyClass;
@property (nullable,nonatomic,readonly)SEL     propertyGetter;
@property (nullable,nonatomic,readonly)SEL     propertySetter;
@property (nonatomic,readonly)BOOL hasKindOfClass;

/**
 Get setter that generated by compiler.
 */
@property (nullable,nonatomic,readonly)SEL     associatedSetter;

/**
 The type written by programmer.Like @"int" , @"NSString".
 */
@property (nonnull,nonatomic,copy,readonly)NSString* programmingType;
@property (nonnull,nonatomic,copy,readonly)NSString* valueAttibute;
@property (nonnull,nonatomic,copy,readonly)NSString* valueTypeEncoding;
@property (nullable,nonatomic,readonly)Ivar   associatedIvar;


/**
 Befor unhook property and remove property from cache.
 */
- (void)invalid;

/**
 Call it when it is accessed.
 */
- (void)access;
- (NSUInteger)accessCount;


/**
 [obj isEqual: @"Srcclass/Desclass.property"] => YES
 */
- (BOOL)isEqual:(nonnull id)object;

/**
 OriginalClass/TargetClass.UserProperty
 */
- (NSUInteger)hash;
#warning change to mappingKeyString
- (nonnull APCStringkeyString*)mappingKey;
@end

